### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).




In [1]:
import numpy as np

N = input('Введине количество элементов массива: ')

try:
    print('\nСформирован массив: \033[1m\n', np.arange(int(N)-1, -1, -1))
except:
    print('\033[1m\033[91mВведены некорректные значения!')



Введине количество элементов массива: 5

Сформирован массив: 
 [4 3 2 1 0]


### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.


In [9]:
import numpy as np

N = input('Введине количество элементов массива: ')
N_ar = np.diag(np.arange(int(N)-1, -1, -1))

try:
    print('\nСформирован массив: \033[1m\n', N_ar)
    print('\n\033[0mСумма диагональных элементов: \033[1m', sum(N_ar[i][i] for i in range(int(N))))    
except:
    print('\033[1m\033[91mВведены некорректные значения!')

Введине количество элементов массива: 8

Сформирован массив: 
 [[7 0 0 0 0 0 0 0]
 [0 6 0 0 0 0 0 0]
 [0 0 5 0 0 0 0 0]
 [0 0 0 4 0 0 0 0]
 [0 0 0 0 3 0 0 0]
 [0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0]]

Сумма диагональных элементов:  28


### Задание 3
Решите систему уравнений:

4x + 2y + z = 4 

x + 3y = 12 

5y + 4z = -3 

In [16]:

a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )

np.linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [17]:
np.allclose( np.dot(a, np.linalg.solve(a, b)), b )

True